<?php

namespace AppBundle\Repository;

/**
 * VSCPClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VSCPClassRepository extends \Doctrine\ORM\EntityRepository
{
  public function GetVSCPClass()
  {

    $em = $this->getEntityManager();
    $query = $em->createQuery("
      SELECT
      a.id,
      a.vscpclass,
      a.vscpclassName,
      a.vscpclassToken,
      a.vscpclassDescription
      FROM AppBundle:VSCPClass a
      ORDER BY a.id
      ");
    return $query->getResult();

  }
}
